### ISSUE TITLE
Image: is an alias of File:

### ISSUE THREAD

**Issue by Dinoguy1000** [daveshap/PlainTextWikipedia#2]
Currently, file embeds beginning with `[[Image:` are removed blindly in `remove_pictures()`, presumably with the thinking that they are always going to be actual images. However, "Image" is just an alias for "File", and therefore //any// file embed can use it, even embeds of audio, video, or the like.

**Comment by daveshap** [comment]
I tested it without checking for "[[Image:" and there were leftover tags. The goal is to have clean plain text.
